# Generated by Django 4.2.4 on 2023-10-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_remove_leadfile_created_by_remove_leadfile_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(default=' ', max_length=11),
        ),
    ]
