# Generated by Django 4.2.4 on 2023-10-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_lead_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='property_type',
            field=models.CharField(choices=[('plot', 'plot'), ('readyTomove', 'readyTomove'), ('apartment', 'apartment')], default='plot', max_length=11),
        ),
    ]
