# Generated by Django 4.2.4 on 2023-10-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_comment_client_remove_comment_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default=' ', max_length=11),
        ),
    ]
