# Generated by Django 4.2.4 on 2023-10-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
    ]
